[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal={family = "CaskaydiaCove Nerd Font", style="Regular"}
size=14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window]
padding	= { x = 10, y = 10 }
